### ISSUE TITLE
Show "empty" days (days with no events)

### ISSUE THREAD

**Issue by denilsonsa** [plusonelabs/calendar-widget#125] opened 2014-07-23 17:06 UTC
It could be interesting to have a setting to display days that have no events.

For instance, suppose that my next event is 4 days from now. Currently, that event shows right after today. My proposal would make the widget show today, tomorrow, the day after, yet another day, and then the day with the event. Showing such "empty" days is useful because it gives a visual sense of how far away the event is.

**Comment by yvolk** [comment] 2015-04-24 03:13
Duplicate of #34, implemented in v.1.9

**Closed by yvolk** 2015-04-24 03:13 UTC
