### ISSUE TITLE
Time Column Width

### ISSUE THREAD

**Issue by gatorheel** [plusonelabs/calendar-widget#301] opened 2019-03-08 22:00 UTC
I use an admittedly very dense setup and am using Nova Launcher and Android 9 which might contribute to my issue.  I have Todo Agenda set up to show one line per event, start time only, and the column width is too small to show the full start time, truncating am/pm on all and the last minute digit for double-digit hours.  Is there a setting I'm missing or is this a bug?

Thanks!
Matt

![Screenshot_20190308-164858_Nova Launcher](https://user-images.githubusercontent.com/2905792/54058193-2794c480-41c3-11e9-896f-254c8e7f07ef.jpg)

**Comment by Nephiel** [comment] 2019-09-02 21:24
Same here:
![Screenshot_20190902-231513_1](https://user-images.githubusercontent.com/2184015/64133700-7faa2d80-cdd8-11e9-934f-daafcc771eee.png)
The issue happens with all font sizes.

**Comment by yvolk** [comment] 2019-09-03 05:29
The problem is caused by my trying to present data in different rows in one column not knowing exact width of each value.
I tried current width on my devices, it's OK, but your screenshots show that in some other cases (other "pixel densities"...) we need wider time column...

Adding "time column width" option would be an overkill? Ok a solution?

**Comment by yvolk** [comment] 2019-09-04 05:19
Should be fixed in v.3.0.1, see Beta at https://play.google.com/apps/testing/org.andstatus.todoagenda
?!

**Comment by Wolve1** [comment] 2019-09-04 17:05
Thank you! It's working properly now after update to 3.0.1!

**Comment by Nephiel** [comment] 2019-09-04 19:02
It is working, thanks!
Though it seems I can't hide the widget header now.

**Comment by yvolk** [comment] 2019-09-05 05:53
@Nephiel If that is a real problem, please start a separate Issue

**Comment by Nephiel** [comment] 2019-09-05 05:58
It seems OK now. I think this one can be closed.

**Closed** 2019-09-05 15:45 UTC
