### ISSUE TITLE
Multiple widgets share the same configuration

### ISSUE THREAD

**Issue by simkin** [plusonelabs/calendar-widget#247] opened 2017-01-11 14:48 UTC
It seems it is not possible to configure each widget independently. This makes it impossible to have a dedicated widget for your work calendar and another for your private calendar.

For me personally this is a must have.

**Comment by yvolk** [comment] 2017-03-24 05:34
Thank you for the suggestion.  This is a duplicate of#37. And we are planning to implement this .

**Closed by yvolk** 2017-03-24 05:34 UTC
