### ISSUE TITLE
No longer in Google play?

### ISSUE THREAD

**Issue by meyerajm** [plusonelabs/calendar-widget#291] opened 2018-06-05 15:47 UTC
I went to Google Play to leave a review because I didn't have an account with GitHub, but I can't find the widget app anywhere. Your link to the Google Play app page also says "item not found." What's going on? Is this widget discontinued?

**Comment by mpost** [comment] 2018-06-05 15:49
We are experiencing problems with the store listing. Please stay tuned.

**Comment by meyerajm** [comment] 2018-06-05 15:51
Ok good. So you're not closing up shop.

**Comment by druckmusik** [comment] 2018-06-06 15:10
Any news on this?
Can the apk be found somewhere elso to download?

**Comment by mpost** [comment] 2018-06-06 18:41
We are in active contact with Google and will keep you updated. Of course you can still build the app from sources.

**Comment by Offerel** [comment] 2018-06-17 07:09
Oh my god. I uninstalled the app by mistake and i didn't have a apk. Is there anything somewhere?

**Comment by Homeuser66** [comment] 2018-06-17 13:46
If it's allowed, I can back up the apk and share it. I just wiped my phone and couldn't find it in the play store again. I have it on my tablet, so I shared it with my phone, now I have it again.

**Comment by Offerel** [comment] 2018-06-17 14:30
That would be great.

**Comment by Homeuser66** [comment] 2018-06-17 15:09
Here is the apk from my phone. Enjoy!

https://drive.google.com/file/d/1wkLQ59uhkK5nujYdE-UlVqkXEZ2vaYiX/view?usp=drivesdk

**Comment by Offerel** [comment] 2018-06-17 20:36
Many thx. I hope the dev. could find a solution with Google to fix the app listing at the store.

**Comment by prediscover** [comment] 2018-07-06 07:12
Any updates?

**Comment by mpost** [comment] 2018-07-06 08:03
Thanks for your interest in the app. At the moment we have no news to report. Out developer account got banned for some unclear reason. We are trying to get in contact with the Google Play team but that turned out to be very difficult.

**Comment by Homeuser66** [comment] 2018-07-06 11:20
Well that just sucks! Sorry to hear this. Hope it gets resolved soon! Thanks for being honest and telling us what's really gong on. It's there anything is end users can do to speed up the process?

**Comment by Offerel** [comment] 2018-07-06 15:49
I have found the app also at F-Droid official Repository. Have a look at  https://f-droid.org/en/packages/com.plusonelabs.calendar/

**Comment by pcolby** [comment] 2018-07-09 05:58
> It's there anything is end users can do to speed up the process?

There must be something the community can do to help get this back into the Play Store?  Is there a Play Store email address we can write to or something?

**Comment by mpost** [comment] 2018-07-09 08:05
We have filed an appeal about our account termination but so far have not gotten any clarification of what exactly has been held against us. We have tried to get in contact with the Google Play team on various channels but so far with no luck.

Here is the docs entry from the Google Play help: https://support.google.com/googleplay/android-developer/answer/9023898?hl=en&ref_topic=15868 (under "Account was terminated").

Here Is the appeal form: https://support.google.com/googleplay/android-developer/contact/protectappeals

**Comment by yvolk** [comment] 2018-07-12 20:17
@mpost Did you use any sort of data collection from users devices' in one of that account's applications? As I remember, several years ago very popular "Dialer One" application was permanently deleted from Play Store for some "statistics" like that...

**Comment by mpost** [comment] 2018-07-13 16:11
@yvolk We got reported for "Impersonation" but are not aware of any wrong doing. We have contact the support again and they said to "ensure a faster resolution of your appeal, I’ve forwarded your message to our Policy team". If that really means anything is up in the air.

**Comment by gravax** [comment] 2018-07-24 18:08
You could put it on the Amazon store...

**Comment by atomicjoy** [comment] 2018-08-14 16:26
Is there any update on this?

**Comment by Homeuser66** [comment] 2018-08-15 10:18
Yeah, are they allowing you back in?

**Comment by mpost** [comment] 2018-08-17 17:47
Thanks for your interest in the app. We have not come to an agreement with the Google Play team yet. We are not giving up and will use other ways of distribution if it comes to it.

**Comment by Homeuser66** [comment] 2018-08-19 14:28
Hope you get it worked out soon!

**Comment by DAVe3283** [comment] 2018-12-19 05:43
Same here. Just got a new phone, and noticed the app didn't transfer. Would love to have it back in the store.

**Comment by mpost** [comment] 2018-12-19 08:11
It is great to hear so much appreciation of this calendar widget. We could still not resolve the Google Play account issues but we decided to move on and and to republish the app. This will give it a new identity in the store so you would need to reinstall. Please stay tuned as the calendar widget will return soon.

**Comment by iloveeclipse** [comment] 2018-12-19 08:13
So far the best calendar widget I've tried. Great work.

**Comment by pr0gg3r** [comment] 2018-12-19 08:16
It's my favourite calendar widget - the best ever made. Thanks a lot.
I'm glad that it is on GitHub, for me no need to deploy it to the Play Store ;)

**Comment by StarCruiser75** [comment] 2018-12-19 08:38
Agree, best calendar widget ever, glad to hear that it will come to new life!!

**Comment by yafp** [comment] 2018-12-19 09:58
@mpost:
Please let us now what the new identifiy is (once it is done). Otherwise we aren't able to locate/find it in Google Play i guess.

Thanks

**Comment by Homeuser66** [comment] 2018-12-19 12:42
@DAVe3283
@yafp
 if you look at my post ☝️, the 9th post. You will see the link to the apk so you can install it again. It you can wait for the new and improved version mpost mentioned.

**Comment by FrankVteZ** [comment] 2018-12-19 22:53
Well I love the widget too. Love to see it again in Google play.

A nice work-around: due to phone policies I'm not able to install non-Google Play apk's.

With the use of "Samsung Smartwitch" (Google play) I transferred the app from my older S6 to my new A8 device and that works like a charm!
And please don't tell my admin :)

**Comment by Homeuser66** [comment] 2018-12-20 00:41
@frankvtez you can install it, just change the setting to allow it

**Comment by FrankVteZ** [comment] 2018-12-20 06:43
@homeuser66 No I cant. Disabled option.

**Comment by Homeuser66** [comment] 2018-12-20 16:09
@frankvtez ok sorry. I am able to, thought you might be able to add well. At least you got it again

**Comment by LocutusX** [comment] 2018-12-22 16:59
Would be a terrific "Christmas" present if this wonderful app/widget got "republished" to the Google Play Store.

I think many of us like this widget so much, we would be willing to donate money (PayPal, etc.)!

**Comment by yvolk** [comment] 2018-12-22 17:43
I'm preparing to publish at Google Play renamed version of the "Calendar Widget" using another developer's account. Other than the new name, which you will know soon... :-), it will be exactly the same as the latest version of the Calendar Widget.

**Comment by yvolk** [comment] 2018-12-23 14:59
The new Calendar Widget app is called "Todo Agenda" and it is available at Google Play: https://play.google.com/store/apps/details?id=org.andstatus.todoagenda
I decided not to associate it with any commercial entity (even with my own .com domain), and this is why I made the Todo Agenda a part of the non-commercial andstatus.org project, and corresponding AndStatus project at GitHub; https://github.com/andstatus/todoagenda

**Comment by Homeuser66** [comment] 2018-12-23 20:36
Excellent! I'm getting it now!




This was sent from my Droid Phone, sorry for any typos...


AL

**Comment by LocutusX** [comment] 2019-01-06 18:50
Hi yvolk,

Appreciate you taking the initiative to resolve this issue!

Is your "version" of this app identical to the original author's version (bit for bit) - and is it also sanctioned by the original author for you to re-publish it?

Thanks.

**Comment by yvolk** [comment] 2019-01-06 19:43
@LocutusX re-published version is _not_ identical to the original one, of course. Even a new name changes an application and can potentially break it. Fortunately, no problems, caused by these changes, were found so far (60 active user installs are reported by Google Play).
Regarding "original author"'s attitude to the widget's re-publishing please read his comment above: https://github.com/plusonelabs/calendar-widget/issues/291#issuecomment-448505900

**Comment by mpost** [comment] 2019-01-07 08:50
@LocutusX Thanks for your interest in the widget. @yvolk and myself have synced the migration and going forward the new app will be the official version in the store. Enjoy responsibly. :)

**Comment by firecat53** [comment] 2019-01-13 20:07
Are you planning on publishing and maintaining the app on f-droid also? Existing version works but is a year and a half old (1.10). Thanks!

**Comment by relan** [comment] 2019-01-14 14:53
F-Droid maintainer here.

A small correction: there's 1.10.1 available on F-Droid, see https://f-droid.org/en/packages/com.plusonelabs.calendar/

As far as I can see 2.0 is identical to 1.10.1. If 2.0 gets an update, ping me and I'll happily add _Todo Agenda_ to F-Droid.

**Comment by yvolk** [comment] 2019-01-19 14:04
@relan So, Todo Agenda v2.0.1 is released with the first, but important fix for Android 8+ (see #298).
Please, add the Todo Agenda to F-Droid.

**Comment by relan** [comment] 2019-01-20 06:04
@yvolk, we can actually add 2.0.1 as an update of 1.10.1, i.e. keeping the old app ID. Should I do this or you'd prefer Todo Agenda to be a new app with the new ID?

**Comment by yvolk** [comment] 2019-01-20 06:12
@relan I thought about this also... 
As we decided to have the renamed application (which has its own forked repo https://github.com/andstatus/todoagenda ) in the master branch of the main repository (thus completely overwriting the old application), I think that it is logical to keep the old application ID and the old repository link.
These are the application name _and_ application package, that changed.

**Comment by yvolk** [comment] 2019-01-20 09:32
@relan I see that currently auto update is turned off:

    Auto Update Mode:None
    Update Check Mode:None

Could we turn it on via something like this:

    Auto Update Mode:Version v%v
    Update Check Mode:Tags v^[0-9.]+$

?!

**Comment by relan** [comment] 2019-01-20 09:40
> Could we turn it on via something like this

Not possible for dynamically generated versionName and versionCode.

**Comment by yvolk** [comment] 2019-01-20 09:42
Got it, thank you.

**Comment by yvolk** [comment] 2019-01-23 18:04
@relan I see that the last build in F-Droid failed. What should we do to fix this?
https://f-droid.org/wiki/page/com.plusonelabs.calendar/lastbuild_425

**Comment by relan** [comment] 2019-01-24 04:45
Google changed their SDK license and now almost all builds fail, see https://gitlab.com/fdroid/fdroidserver/issues/620

**Comment by yvolk** [comment] 2019-01-24 06:15
@relan So we're waiting for a fix at f-droid server end?!

**Comment by relan** [comment] 2019-01-24 06:16
Yes. Nothing to do on your side.

**Closed** 2019-02-19 16:58 UTC

**Comment by yvolk** [comment] 2019-10-07 06:29
@relan Recently I noticed that this was just a one time publishing in F-Droid. I created merge request for an update, and now waiting for somebody to approve it.
Could you please look at it https://gitlab.com/fdroid/fdroiddata/merge_requests/5561#note_226646364
