### ISSUE TITLE
Google Reminders not supported/visible

### ISSUE THREAD

**Issue by fredphoesh** [plusonelabs/calendar-widget#230] opened 2016-04-18 10:26 UTC
Google has rolled out it's new Reminders for Google Calendar... and IMO this aspect of Calendar really should be supported by the widget.

Thanks
Mark.

**Comment by kennethscott** [comment] 2016-05-19 02:29
+1

**Comment by erikgeurts** [comment] 2016-06-20 09:39
I would like to ask for support for reminders in the widget.

**Comment by saescott** [comment] 2016-06-21 07:54
+1, reminders is very important.

**Comment by tomchiverton** [comment] 2016-07-01 10:03
Just noticed this today

**Comment by magcsaba** [comment] 2016-07-10 09:38
+1

**Comment by yvolk** [comment] 2016-07-13 05:41
This is a duplicate of #220 
Please discuss there.

**Closed by yvolk** 2016-07-13 05:41 UTC
