### ISSUE TITLE
No more update

### ISSUE THREAD

**Issue by stemy2** [plusonelabs/calendar-widget#303] opened 2019-03-24 20:50 UTC
Hello,

Since an undefined time, the updates are not applied to the widget, but are in my local calendar. I added a new online ics source with the app icsx5, but nothing changed in the widget, only in my local calendar.

I reinstalled the app, and now, the widget is empty whatever i do.

**Comment by yvolk** [comment] 2019-03-25 16:25
Looks like a duplicate of https://github.com/plusonelabs/calendar-widget/issues/302 , please see that issue.

**Closed by yvolk** 2019-03-25 16:25 UTC

**Comment by stemy2** [comment] 2019-03-25 16:31
No, it's not. My problem has nothing to do with the update button, it's about an automatic update that doesn't work anymore.

**Comment by yvolk** [comment] 2019-03-25 16:37
As I found out during investigation https://github.com/plusonelabs/calendar-widget/issues/298 button not working and no automatic updates are related problems, caused by changing Android rules. Please read discussion in #298, maybe you will figure out the cause of your current problem.
