### ISSUE TITLE
All day events: Remove Old Events

### ISSUE THREAD

**Issue by kaneelias** [plusonelabs/calendar-widget#188] opened 2015-08-23 23:43 UTC
Since the update I now have all day events eg. birthdays from the previous day showing.

I tried adding an exception for "Birthday" in the keywords but that removes future events as well.

How can i get rid of this because it looks ridiculous and is not needed.

Thanks

**Comment by yvolk** [comment] 2015-08-24 05:41
1. Please start from reading the latest entry in a Changelog here: https://github.com/plusonelabs/calendar-widget
2. In order to hide all past events goto Settings -> Event filters - and make sure you have turned off both entries under the "Past events" group of settings.

**Comment by kaneelias** [comment] 2015-08-24 05:48
Thanks, I have read the changelog and both those settings are disabled already

**Comment by yvolk** [comment] 2015-08-24 06:26
So, is the problem solved, or you still see yesterday's all day event?
(I tried this now and I don't see it...)

**Comment by kaneelias** [comment] 2015-08-24 22:54
Nope, still the same problem. I had a birthday in my calendar yesterday and today it is still showing with a different background even with past events disabled.

I have also found that recurring future events have disappeared. I have a recurring event that happens every day monday to friday in my calendar and it is only showing today.

I rolled back to the previous version and the recurring event is showing on all days like it should and the previous days birthday is gone like it should.

This update has messed up quite a lot of stuff which is disappointing as this was such a good widget.

**Comment by yvolk** [comment] 2015-08-25 05:28
I think that the problem with yesterday's birthday is caused by different time zones:
1. One, in which your birthday is defined
2. Another time zone, which is set now on your Android device.

Could you check and post here:
1. Full information about the birthday, which is shown in a Calendar application (i.e. when you open the event, clicking on it in the Widget): 
1.1. Is it marked as a "All day event" ?
1.2. What Start and end times (with time zones) are shown?

2. Time zone of your device.

**Comment by kaneelias** [comment] 2015-08-25 06:05
I can confirm that after 12:00pm Australian time the birthday from yesterday has gone.

As an example with the birthday the date shows Monday 24th of August to Tuesday the 25th of August so at midnight Tuesday this should be removed.

These are birthdays pulled from Facebook. On my phone I have rolled back these are cleared on the newest version on my tablet these are not cleared. Time zone on both is +10 GMT

**Comment by kaneelias** [comment] 2015-08-25 06:06
PS. These are shown as all day events

**Comment by yvolk** [comment] 2015-08-25 06:23
Thank you for information. We are in a process of creating test cases for all such unusual events, so we need help in correct identification of such events. 
Regarding this case with birthday, I still think that birthdays in that Facebook calendar are in some other time zone. You wrote that Facebook birthdays are on GMT  +10 . How do you know that? Could you post a screenshot of that event? (With private data erased. ..)
Please note also that Android itself has some issues with calendars and time zones... So even the data, which you see in the opened event may be not the same as the data about the same event, which Calendar-widget receives.
BTW, please try to open that Birthday in different Calendar applications. E.g. in the Google Calendar and in some other,  e.g. provided by a phone vendor.

**Comment by kaneelias** [comment] 2015-08-25 06:26
Hi thanks for the reply. Sorry I said the data is coming from facebook but both devices are in the +10GMT time zone.

I have opened the event in multiple calendars, sunrise, google calendar and no issue

Like I said the previous build of the widget handles this perfectly so I believe something is broken in the new release.

**Comment by yvolk** [comment] 2015-08-25 06:35
There is no doubt that something is broken in current release. The main question is how to fix one issue and not to create another. 
E.g. as I wrote above, I created a birthday as a yesterday's all day event in my calendar. And I couldn't see it in a widget, as expected... So I still cannot reproduce the problem. 

What Android version do you have?

**Comment by kaneelias** [comment] 2015-08-25 06:45
I am running CM12 5.0.2

**Comment by yvolk** [comment] 2015-08-25 07:23
@kaneelias You wrote that the Birthday event is in GMT +10, but you still didn't provide a screenshot that shows that. 
I'm asking for this again, because when _I_ opened my test "birthday", which works correctly in the Widget,  I didn't find _any_ information on a time zone shown in it...

Please try to create now new birthday ("Birthday 2") and check if it is shown correctly in the Widget.

**Comment by kaneelias** [comment] 2015-08-25 11:10
Sorry for the confusion I did not say that the even was in +10 gmt. My devices are +10gmt and the birthdays are pulled directly from Facebook

**Comment by mjt543** [comment] 2015-08-26 03:30
I have a similar issue. Both past event settings are disabled, however, a multi-day event that started the previous day and continues through today keeps yesterday's date and that calendar entry visible in the widget. In the previous iteration of the widget, yesterday's entry would have disappeared around 8 pm central time, which is what I would prefer over the current outcome.

**Comment by mpost** [comment] 2015-08-26 19:12
I have to agree with @mjt543. Having a two day long event which spans yesterday and today should not show up yesterday when all settings to show previous events are disabled.

**Comment by yvolk** [comment] 2015-08-27 06:38
Today I see the same behavior with a Birthday showing one day earlier in a Google Calendar application on my Samsung Galaxy Tab Pro. 
See the screenshot attached: it shows the birthday as a two days event!  While it should be on September 9 only. 
![screenshot_2015-08-27-09-27-51](https://cloud.githubusercontent.com/assets/207716/9514048/154cc7f4-4c9f-11e5-8651-c7da4a68f776.png)

**Comment by mpost** [comment] 2015-08-27 07:27
I had an issue like that as well

**Comment by 41south** [comment] 2015-08-29 23:55
Same issue with past all day events here, pain in the backside, hope it gets fixed soon.

**Comment by Offerel** [comment] 2015-08-30 14:38
I have the same problem since the last update.

**Comment by yvolk** [comment] 2015-08-31 12:46
@kaneelias Using a newly introduced Testing framework, I was able to reproduce problems with multi day events, but I still cannot reproduce your problem with a One day event: Birthday.
I even created a new item in a Settings -> Feedback -> "Share events for debugging", which I kindly ask you to use and share data with us, if you still have a problem with a birthday from previous days showing even when options to show past events are turned off.
More on the "Share events for debugging" feature here: https://github.com/plusonelabs/calendar-widget/issues/190#issuecomment-136359880

**Comment by yvolk** [comment] 2015-09-02 07:06
@kaneelias In the latest commit filtering of All day events improved. Now yesterday's birthday will disappear at 00:00 local time next day (covered by a test case).
BTW, you may build and test current repository code at your device using AIDE Android application (  https://play.google.com/store/apps/details?id=com.aide.ui )

**Comment by kaneelias** [comment] 2015-09-02 07:11
Sorry, where can I download the new APK to test?

**Comment by 41south** [comment] 2015-09-05 22:32
Same question, where can I download the latest version to test?

**Comment by mpost** [comment] 2015-09-05 23:24
Currently you have to build it from source.

**Comment by yvolk** [comment] 2015-09-08 11:24
Calendar widget is published to a beta testing channel.  Please join testing at https://play.google.com/apps/testing/com.plusonelabs.calendar

**Comment by kaneelias** [comment] 2015-09-09 00:34
Thanks I have signed up and will test. Is there are way to check on android if the Beta is installed?

**Comment by yvolk** [comment] 2015-09-09 06:14
Google Play requires each version of an application to have unique Version code. Current Beta has version code 29. This Beta may become a release, this is why there are no other differences. 
You may lookup version code of currently installed Calendar-widget e.g. in a data, shared via Settings -> Feedback -> Share events for debugging.

**Comment by mpost** [comment] 2015-09-09 07:26
At the moment you can also check the version number which reads <code>1.9.2</code>.

**Comment by kaneelias** [comment] 2015-09-09 07:42
Cool that is what I have got.

**Comment by 41south** [comment] 2015-09-10 20:16
My problem with all day events is fixed with the test version, thanks!

**Comment by kaneelias** [comment] 2015-09-11 00:27
Mine seems to be working as well.

**Comment by Offerel** [comment] 2015-09-11 07:04
I dont know if this issue occurs first since this fix in the latest beta. However if i have for intance a event today, with start 08:30 and the event ends 11:00 and i turn on the Phone 08:46 (or hit the refresh button at this time), the event displays starting at the refresh time.

**Comment by mpost** [comment] 2015-09-12 08:39
@Offerel I can confirm this regression. We should fix that before pushing the 1.9.2 update. I have opened a new issue for that: https://github.com/plusonelabs/calendar-widget/issues/199

**Comment by kaneelias** [comment] 2015-09-18 23:22
Not sure if this is a bug in the beta but when I have an active event eg start time is 8:30am till 11:30am. When I check my phone at 9:17 the start time in the widget now shows 9:17 so the current time. 

I am not a fan of this. Can it be disabled?

**Comment by mpost** [comment] 2015-09-19 06:07
That is already fixed inhttps://github.com/plusonelabs/calendar-widget/issues/199. Please try the latest beta release.

**Comment by mpost** [comment] 2015-10-22 12:26
Closing this as fixed.

**Closed by mpost** 2015-10-22 12:26 UTC
Labels: bug
