### ISSUE TITLE
Feature request: Ability to choose calendar app and to just open it

### ISSUE THREAD

**Issue by ktaragorn** [plusonelabs/calendar-widget#150] opened 2014-10-21 03:25 UTC
My personal preference is for any click on the widget to just open my third party Calendar app Business in the default Month view. Perhaps a new "Click Behavior" settings panel to control this

**Comment by Shadowigor** [comment] 2017-09-24 09:55
This seems to be a quite old issue, but I'd like that as well. Will this be implemented at some point?

**Comment by yvolk** [comment] 2017-09-25 05:45
This is a duplicate of an answered question https://github.com/plusonelabs/calendar-widget/issues/238
Please see there how to setup this.

**Closed by yvolk** 2017-09-25 05:45 UTC

**Comment by Shadowigor** [comment] 2017-09-25 07:10
No, this is not a duplicate. #238 is refering to opening a single event in a third party calendar. That's already working by default for me. What this is about is opening the default view of a calendar, NOT the event itself, when you click anywhere on the widget.

**Comment by yvolk** [comment] 2017-09-25 15:49
I just tried clicking on a date in the Calendar Widget's header. Just like clicking on a single event, Android prompts me for a Calendar application to use:
![screenshot_20170925-184506](https://user-images.githubusercontent.com/207716/30817653-1697f55e-a222-11e7-9845-e6fcc7115515.png)

**Comment by Shadowigor** [comment] 2017-09-25 16:08
Yes, that's working, that's not the problem. The behavior I was looking for, was that tapping **anywhere** on the widget would open the calendar and never a specific event. Even with the header disabled.

**Comment by yvolk** [comment] 2017-09-26 06:00
@Shadowigor This means that we closed _this_ issue correctly. Your request is not about it.
In order for _your_ request to be clearly stated and not confused with others, you could  create new issue with focused title and detailed description.

**Comment by ktaragorn** [comment] 2017-09-26 06:12
Actually I think my issue is the same as he is describing

**Comment by yvolk** [comment] 2017-09-26 15:25
@ktaragorn Good, now you could formulate your wish better :-)
In a new "issue", please.

**Comment by ktaragorn** [comment] 2017-09-27 03:24
Why cant it just be reopened? Isnt that what that button is designed for? To reopen tickets that were prematurely closed.

**Comment by yvolk** [comment] 2017-09-27 05:22
@ktaragorn This is a methodological/development process question.
This issue was created with another subject and description. According to _that_ information it was discussed and is now closed correctly.
Reopening the issue and changing its subject/description would be confusing, because previous conversation was about another subject.
This is why creation of a new issue with new subject (and without a history of discussion of another subject) will be the right way to communicate your wish to developers.

**Comment by ktaragorn** [comment] 2017-09-27 05:49
@Shadowigor follow the issue at #270
