### ISSUE TITLE
Calendar widget does not appear in list of widgets

### ISSUE THREAD

**Issue by mpost** [plusonelabs/calendar-widget#165] opened 2015-02-25 13:06 UTC

**Comment by yvolk** [comment] 2015-02-28 05:47
Currently this looks like incompatibility with some Android version or with a device Model.
If you have the same problem, please post your device "Model number" and "Android version" here (the information is here: Settings -> About phone -> "Model number" / "Android version")

**Comment by erolfox** [comment] 2015-03-03 08:06
No widget on Nexus 5 lollipop

**Comment by yvolk** [comment] 2015-03-04 19:10
I tried this on an Emulator, selecting Nexus 5 + Lollipop virtual device, installed the latest published version of a Calendar-Widget (1.8.6) - and I do see the widget in the "Widgets" list, see a screenshot below.
![scr-nexus-5-lollipop](https://cloud.githubusercontent.com/assets/207716/6490970/1e35bec0-c2bb-11e4-9fc0-53875dc0da6a.png)

**Comment by erolfox** [comment] 2015-03-04 21:01
Wow! I see it note too.
I rebooted yesterday. Maybe that made it show up? Could explain the other folks seeing this behavior.
Thanks Yuri!
On Mar 4, 2015 11:10 AM, Yuri Volkov <notifications@github.com> wrote:I tried this on an Emulator, selecting Nexus 5 + Lollipop virtual device, installed the latest published version of a Calendar-Widget (1.8.6) - and I do see the widget in the "Widgets" list, see a screenshot below.

**Comment by erolfox** [comment] 2015-03-05 07:05
Yes, that's it. Tested on my tablet. A reboot is required for the widget to show up . Strange
On Mar 4, 2015 11:10 AM, Yuri Volkov <notifications@github.com> wrote:I tried this on an Emulator, selecting Nexus 5 + Lollipop virtual device, installed the latest published version of a Calendar-Widget (1.8.6) - and I do see the widget in the "Widgets" list, see a screenshot below.

**Comment by yvolk** [comment] 2015-03-06 14:08
This is sort of Android platform "feature", see e.g. http://stackoverflow.com/questions/6024025/android-appwidget-does-not-show-up-in-the-menu-in-honeycomb-until-reboot
For now I've added android:installLocation="internalOnly" to manifest only, as suggested in a solution.
Next time, when I will encounter this behavior, I will try to launch "Calendar Widget" activity from Android "Apps" - this should also force Android Launcher to update a list of Widgets.

**Comment by mpost** [comment] 2015-03-06 16:42
The referenced so post looks rather old but if the internal flag helps I am all for it.

**Comment by mjdetullio** [comment] 2015-03-08 00:22
Can confirm, was not showing up for me today after installing, so I rebooted and that fixed it.

Tested on 2014 Moto X, Android 5.0, Google Now Launcher

**Comment by yvolk** [comment] 2015-03-08 14:35
@mpost Yes, that posts are old, and corresponding Android bug is marked as "obsolete". I saw the same problem in another application in Android emulator v.4.4, but later it looks like something was fixed in emulator (and in Android core).
And now it reappears in Android v.5 ?!

**Comment by erolfox** [comment] 2015-03-13 20:07
Bug and workaround:
A reboot is required on lollipop to have the widget appear in the list of widgets.

**Comment by kemelzaidan** [comment] 2015-07-06 17:40
Confirmed on Motorola XT1078 (Moto G second Generation with 4G LTE) with Lollipop 5.0.2

**Comment by yvolk** [comment] 2019-10-13 09:38
Closing as outdated.
Anyway, this is not the widget's issue, but the Launcher's one.

**Closed by yvolk** 2019-10-13 09:38 UTC
