### ISSUE TITLE
Repeat events missing on certain days, strange color block at top of app 

### ISSUE THREAD

**Issue by cgonz2** [plusonelabs/calendar-widget#200] opened 2015-09-16 17:58 UTC
I have three events this week that are scheduled as all-day events lasting from the 14th to the 18th. When I view the event individually, the dates and times are displayed correctly. However, on the widget that sits on my phone screen, each of these events shows up on certain days, but skip other days in which they should appear.

Also, there is a strange color block across the top of the app that appeared recently that did not used to be there. I've tried removing the widget from the screen and adding it back to refresh; this has not helped.

Including a picture for reference. In the picture, you can see that Sept. 16th and 17th are displaying all 3 events, which is correct, but Sept. 14th and 15th are not, even though they should be. Also, screenshot was taken on the 16th - should Sept. 14th and 15th not be displaying at all?
![screenshot_2015-09-16-12-48-37](https://cloud.githubusercontent.com/assets/14317714/9913459/8eed08f2-5c72-11e5-9633-4176c26cc9a6.png)

**Comment by yvolk** [comment] 2015-09-16 18:40
It looks like you noticed the same problem as discussed in #184. Please join Please join testing at https://play.google.com/apps/testing/com.plusonelabs.calendar and see if the problem is already fixed in v.1.9.2 (Beta release)

**Closed** 2019-09-17 18:39 UTC
