### ISSUE TITLE
[Feature Request] Hide calendar colors

### ISSUE THREAD

**Issue by lottanbettan** [plusonelabs/calendar-widget#275] opened 2017-11-18 19:43 UTC
Hi, great widget!
Would be nice with a setting to hide the calendar colors to the left of each event. That would make it look more clean and balanced, and would give some extra width for text instead.
Cheers.

**Comment by MarcSN311** [comment] 2018-04-20 15:16
seems to be a duplicate of: #174

**Closed** 2019-08-24 19:51 UTC
